// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: localharness.proto

package localharness

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	LanguageVersion string                 `protobuf:"bytes,3,opt,name=language_version,json=languageVersion,proto3" json:"language_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_localharness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_localharness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_localharness_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ClientInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfo) GetLanguageVersion() string {
	if x != nil {
		return x.LanguageVersion
	}
	return ""
}

type InputConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StorageDirectory string                 `protobuf:"bytes,1,opt,name=storage_directory,json=storageDirectory,proto3" json:"storage_directory,omitempty"`
	Port             uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	BindAddress      string                 `protobuf:"bytes,3,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	ClientInfo       *ClientInfo            `protobuf:"bytes,4,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InputConfig) Reset() {
	*x = InputConfig{}
	mi := &file_localharness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputConfig) ProtoMessage() {}

func (x *InputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_localharness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputConfig.ProtoReflect.Descriptor instead.
func (*InputConfig) Descriptor() ([]byte, []int) {
	return file_localharness_proto_rawDescGZIP(), []int{1}
}

func (x *InputConfig) GetStorageDirectory() string {
	if x != nil {
		return x.StorageDirectory
	}
	return ""
}

func (x *InputConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InputConfig) GetBindAddress() string {
	if x != nil {
		return x.BindAddress
	}
	return ""
}

func (x *InputConfig) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type OutputConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputConfig) Reset() {
	*x = OutputConfig{}
	mi := &file_localharness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputConfig) ProtoMessage() {}

func (x *OutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_localharness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputConfig.ProtoReflect.Descriptor instead.
func (*OutputConfig) Descriptor() ([]byte, []int) {
	return file_localharness_proto_rawDescGZIP(), []int{2}
}

func (x *OutputConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OutputConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_localharness_proto protoreflect.FileDescriptor

const file_localharness_proto_rawDesc = "" +
	"\n" +
	"\x12localharness.proto\x12\flocalharness\"m\n" +
	"\n" +
	"ClientInfo\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10language_version\x18\x03 \x01(\tR\x0flanguageVersion\"\xac\x01\n" +
	"\vInputConfig\x12+\n" +
	"\x11storage_directory\x18\x01 \x01(\tR\x10storageDirectory\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12!\n" +
	"\fbind_address\x18\x03 \x01(\tR\vbindAddress\x129\n" +
	"\vclient_info\x18\x04 \x01(\v2\x18.localharness.ClientInfoR\n" +
	"clientInfo\";\n" +
	"\fOutputConfig\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKeyBHZFgithub.com/romaine-life/tank-operator/backend-go/internal/localharnessb\x06proto3"

var (
	file_localharness_proto_rawDescOnce sync.Once
	file_localharness_proto_rawDescData []byte
)

func file_localharness_proto_rawDescGZIP() []byte {
	file_localharness_proto_rawDescOnce.Do(func() {
		file_localharness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localharness_proto_rawDesc), len(file_localharness_proto_rawDesc)))
	})
	return file_localharness_proto_rawDescData
}

var file_localharness_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_localharness_proto_goTypes = []any{
	(*ClientInfo)(nil),   // 0: localharness.ClientInfo
	(*InputConfig)(nil),  // 1: localharness.InputConfig
	(*OutputConfig)(nil), // 2: localharness.OutputConfig
}
var file_localharness_proto_depIdxs = []int32{
	0, // 0: localharness.InputConfig.client_info:type_name -> localharness.ClientInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_localharness_proto_init() }
func file_localharness_proto_init() {
	if File_localharness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localharness_proto_rawDesc), len(file_localharness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_localharness_proto_goTypes,
		DependencyIndexes: file_localharness_proto_depIdxs,
		MessageInfos:      file_localharness_proto_msgTypes,
	}.Build()
	File_localharness_proto = out.File
	file_localharness_proto_goTypes = nil
	file_localharness_proto_depIdxs = nil
}
