apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.terminalProxy.configMap }}
  namespace: {{ .Values.namespaces.sessions }}
data:
  config.yaml: |
    authorization:
      resourceAttributes:
        apiGroup: terminal.tank-operator.io
        resource: sessions
        namespace: {{ .Values.namespaces.sessions }}
