apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.terminalProxy.configMap }}
  namespace: {{ include "tank-operator.sessionsNamespace" . }}
data:
  config.yaml: |
    authorization:
      resourceAttributes:
        apiGroup: terminal.tank-operator.io
        resource: sessions
        namespace: {{ include "tank-operator.sessionsNamespace" . }}
